title: [Genomics form the ground up]
description: [New to genomics and struggling? I've been there. I can help and we can cope together]
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
